; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp12e]
platform = espressif8266
board = esp12e
framework = arduino
monitor_speed = 115200
<<<<<<< HEAD
lib_deps = crankyoldgit/IRremoteESP8266@^2.9.0
=======
lib_deps = 
	https://github.com/IdlanZafran/RapidBootWiFi.git
	https://github.com/IdlanZafran/ThingsSentral.git
>>>>>>> d7ebdcf (Initial commit: ESP8266 IoT Remote Buzzer Alarm)
